# Generated by Django 5.1.1 on 2024-09-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Super_Admin', 'Super_Admin'), ('NGO_Admin', 'NGO_Admin'), ('User_admin', 'User_Admin'), ('Query_Admin', 'Query_Admin')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('User', 'User'), ('Admin', 'Admin')], max_length=50, null=True)),
            ],
        ),
    ]
